version: '3'
services:
  axum_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db-postgres:
    image: 'postgres:latest'
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - ./database/data:/docker-entrypoint-initdb.d/